apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2048
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app-2048
  template:
    metadata:
      labels:
        app: app-2048
    spec:
      containers:
      - image: public.ecr.aws/l6m2t8p7/docker-2048:latest
        name: app-2048
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "60Mi"
            cpu: "65m"
          limits:
            memory: "65Mi"
            cpu: "70m"
